### ISSUE TITLE
Wrong Version

### ISSUE THREAD

**Issue by bthedorff** [CokePokes/AppStorePlus-TrollStore#3]
iPhone 8 on iOS 15.6 with pogo and Trollstore

Wrong version is shown after install of new ipa

Uninstalled the old version of Appstore++ from my phone through TrollStore, did a rebuild icon cache and respring through TrollStore. After that I did a uicache and respring through pogo. I install the new version of AppStore++ downloaded from your github and TrollStore still shows version 1.0.2 instead of 1.2-1.

**Comment by CokePokes** [comment]
This was fixed. I’ll bump the minor version from now on.
