### ISSUE TITLE
Feature suggestion: able to identify pulled apps and mark them in the list with a different background color or a character

### ISSUE THREAD

**Issue by mailinglists35** [CokePokes/AppStorePlus-TrollStore#4]
I have an old jb phone with tons of legit downloaded apps. When I restored its' backup to a new stock phone, I was unhappy to discover that many apps were pulled, even if they still have their icons.

Could you be able to make the app identify the pulled apps? You would have to have a way to programatically get the store id then see if request to that url gives you http 200 or 404

US store would be sufficient for me. troll store version or jb version would equally help,

Thank you!

example of app I paid for (and was able to get it back using this guide https://gist.github.com/minif/473310d7c556caadf4f2ed2d97389574)
`user@host ~ $ HEAD https://apps.apple.com/us/app/pro-hdr-x/id927823151`
`404 Not Found`

**Comment by CokePokes** [comment]
I’ve thought about this, but some people have an extensive amount of apps installed & populating and checking every app installed could be too extensive for just a UI change.

**Comment by mailinglists35** [comment]
@CokePokes I'm not sure I understand what would be the difference (in the app code logic) between low number of apps and high number of apps. Is it about load sent to Apple servers? or load sent to AppStore++ servers?

Perhaps a manual check, limited to once a week, would aleviate it?
